### PR TITLE
initial support for command-line arguments

### PR DESCRIPTION
**Pull request by pganson**

### CODE REVIEW

**Comment by pganson** [comment]
I also updated .gitignore to prevent upload of the .idea folder

**Comment by ChristopherKing42** [comment]
If I might ask, why was the copyright notice removed? If you are wondering why it was there, see http://www.gnu.org/licenses/gpl-howto.html. You may add your name to it as well. (Note: you can still work on the branch and it will update this page.)

**Comment by ChristopherKing42** [comment]
Other than that, it seems pretty cool!

**Comment by ChristopherKing42** [comment]
(Oh, and this isn't a big problem, but since PyCharm is specific to your computer, and not the the project, it would be more useful to put it in https://help.github.com/articles/ignoring-files/#create-a-global-gitignore.)

**Comment by pganson** [comment]
Mea culpa re the copyright notice, that was inadvertent - I copy/pasted my code instead of updating yours.  I'll fix it on my local and request a new pull.  Still learning ...

**Comment by pganson** [comment]
I'll look into the global .gitignore, thanks.

**Comment by ChristopherKing42** [comment]
Okay, do you want me to a copyright line for you too? (We technically both own the copyright now, and we collectively allow others to edit.)

**Comment by pganson** [comment]
Thanks but the copyright isn't necessary.  I'm just happy to contribute and learn.

**Comment by ChristopherKing42** [comment]
Thanks, (will just keep the thing in .gitignore for now.)

**Comment by pganson** [comment]
I restored the copyright in the .py file.  I just noticed that the docstring in closings() needs updating.  

also, I didn't ask about the command-line flag convention that you wanted to use ("--usecache" vs. "-usecache", etc.) and just picked one.

**Comment by ChristopherKing42** [comment]
Yea, I noticed to. Also, double lines is standard for long arguments, so that was good. :+1:

**Pull request merged**
